### PR TITLE
adding all supported storage classes for s3 output

### PR DESCRIPTION
**Pull request by jsvd**
Migrated from https://github.com/logstash-plugins/logstash-output-s3/pull/262

closes https://github.com/logstash-plugins/logstash-output-s3/issues/246

### CODE REVIEW

**Comment by jsvd** [comment]
@logstashmachine bump patch

**Comment by jsvd** [comment]
thanks @uday3110 , I moved your PR here (retaining ownership in the commit). I'll be merging and publishing it now.

**Comment by jsvd** [comment]
Published as [logstash-integration-aws 7.1.8](https://rubygems.org/gems/logstash-integration-aws/versions/7.1.8-java)

**Comment by flexitrev** [comment]
Thanks also to @fdh-td for submitting a similar PR https://github.com/logstash-plugins/logstash-integration-aws/pull/43

**Pull request merged**
